config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  devise_for :users
  resources :uniusers
  resources :buy_records
  resources :managers do
    collection do
      get :check_out, path: 'check_out/:id'
      get :buy_record, path: 'buy_record/:id'
    end
  end
  resources :products
  resources :categories do
  	resources :products, :controller => 'categories'
  end
  resource :cart, only:[:show, :destroy] do
    collection do
      post :add, path: 'add/:id'
    end
  end
  root :to => "managers#home"
  get '/show_date' => 'managers#show_date', :as => "show_date"
  patch 'product_update/:id' => 'categories#product_update'
  post '/save_and_destroy' => 'carts#save_and_destroy'
  get '/check_stock' => 'managers#check_stock', :as => "check_stock"
  patch '/update_stock' => 'managers#update_stock', :as => "update_stock"
  patch '/add_user_money' => 'uniusers#add_user_money', :as => "add_user_money"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart
	attr_reader :items, :total

	def initialize(items = [])
		@items = items
	end

	def add_item(product_id)
		found_item = items.find { |item| item.product_id == product_id}
		
		if found_item
			found_item.increment
		else
		@items << CartItem.new(product_id)
		end
	end

	def empty?
		@items.empty?
	end

	def total_price
		items.reduce(0) { |sum, item| sum + item.price }
	end

	def serialize
		all_items = items.map { |item| 

			{ "product_id" => item.product_id, "quantity" => item.quantity }
		}
		{ "items" => all_items }
	end

	def self.from_hash(hash)
		if hash.nil?
			new []
		else
			new hash["items"].map { |item_hash|

				CartItem.new(item_hash["product_id"], item_hash["quantity"])
			}
		end
	end
end

app/models/cart_detail.rb
class CartDetail < ApplicationRecord
	belongs_to :cart_record
end

app/models/cart_item.rb
class CartItem
	attr_reader :product_id, :quantity

	def initialize(product_id, quantity = 1)
		@product_id = product_id
		@quantity = quantity
	end

	def increment(n = 1)
		@quantity += n
	end

	def product
		Product.find_by(id: product_id)
	end

	def price
		product.price * quantity
	end

end

app/models/cart_record.rb
class CartRecord < ApplicationRecord
	has_many :cart_details
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	delegate :name, :to => :category, :prefix => true, :allow_nil => true
end

app/models/replenish.rb
class Replenish < ApplicationRecord
end

app/models/replenish_detail.rb
class ReplenishDetail < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	def add

		current_cart.add_item(params[:id])
		session[:cart9999] = current_cart.serialize

		redirect_to products_path, notice: "#{Product.find(params[:id]).name} 已加入購物車"
	end
	def destroy
		session[:cart9999] = nil

		redirect_to products_path, notice: "購物車已清空"
	end

	def save_and_destroy

		if enough_money?(total)

			@cartrecord = CartRecord.new
			@cartrecord.user_id = current_user.id
			@cartrecord.user_name = current_user.name
			@cartrecord.total_price = current_cart.items.reduce(0) { |sum, item| sum + item.price }

			current_cart.items.each do |item|
				@cartdetail = @cartrecord.cart_details.build
				@cartdetail.product_name = item.product.name
				@cartdetail.quantity = item.quantity
				@cartdetail.unit_price = item.product.price
				@cartdetail.product_subtal = item.price
				@cartdetail.save
			end
			@cartrecord.save

			current_user.money -= total 
			current_user.save

			session[:cart9999] = nil
			redirect_to managers_path, notice: "已付款!於個人首頁查看訂單XXXX狀態" 
		else
			flash.now[:warning] = '餘額不足'
			render 'managers/index'
		end
	end

end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
	def home
	end
	def index
	end
	def create
	end

	def buy_record
		@buyrecords = CartRecord.all
	end
	
	def check_out
	end
	def show_date
		@b = Time.now
	end
	def update 
	end
	def check_stock
		@products = Product.where("in_stocks < safety_stocks")

	end
	def update_stock	
		@products = Product.where("in_stocks < safety_stocks")
		#in_stock 個別增加管理者輸入之值,save個別儲存
		@products.each do |product|
			params[:add_number].each do |key,value|
				puts product.id
				puts key
				puts value
				if key.to_i == product.id
				product.in_stocks += value.to_i
				end
			end
			product.save
		end
		redirect_to managers_path
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, :only => [ :show, :edit, :update, :destroy]
	def index
		@users = User.all
	end
	def new
		@user = User.new
	end
	def create
		@user = User.new(user_params)
		@user.save

		redirect_to users_url
	end
	def show
	end
	def edit
	end
	def update
		@user = User.find(params[:id])
		@user.update(user_params)

		redirect_to user_url(@user)
	end
	def destroy
		@user.destroy
		redirect_to users_url
	end


private
	def set_user
  		@user = User.find(params[:id])
	end
	def user_params
	  params.require(:user).permit(:email, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buy_records_helper.rb
module BuyRecordsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
	def current_cart
		@cart ||= Cart.from_hash(session[:cart9999])
	end

	def has_cart?
		!current_cart.items.empty?
	end

	def total
		current_cart.items.reduce(0) { |sum, item| sum + item.price }
	end


  def enough_money?(total_price)
  	current_user.money > total_price
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/managers/buy_record.html.erb
<style>
	p { margin: 0px; }
</style>

<ol>
	<% @buyrecords.each do |b| %>
		<% if b.user_id = current_user.id %>
	<li>
		<p>使用者姓名: <%= b.user_name %></p>
		<p>購買總價: <%= b.total_price %>
		<p>購買日期: <%= b.created_at.to_date %></p>
		<%= link_to '詳細內容', buy_record_path(b) %>
	</li>
		<% else return b %>
		<% end %>

	<% end %>


</ol>



<%= link_to '回到個人首頁', managers_path %>

app/views/managers/buy_record_details.html.erb

  <thead>
    <tr>
      <td>商品名稱</td>
      <td>數量</td>
      <td>單價</td>
      <td>小計</td>
    </tr>
  </thead>  

  <tbody>
    <% .each do |item| %>
    <tr>
      <td><%= item.product.name %></td>
      <td><%= item.quantity %></td>
      <td><%= item.product.price %></td>
      <td><%= item.price %></td>
    </tr>
    <% end %>
  </tbody>
  <br>
  <tfoot>
    <tr>
      <td colspan="3">總計</td>
      <td><%= current_cart.total_price %></td>
    </tr>
  </tfoot>

app/views/managers/check_out.html.erb


<%= p current_cart %>

<%= puts current_cart %>

<%= print current_cart %>

<%= form_for @product, :url => product_path(@product), :method => :patch do |f| %>
	<%= f.label :user_name, "姓名:" %>
	<%= f.text_field :user_name %><br>
	<%= f.label :telephone, "電話:" %>
	<%= f.text_area :telephone %><br>


	<%= f.submit "確認結帳" %>
<% end %>

app/views/managers/check_stock.html.erb
<%= form_tag update_stock_path(@products), :method => :patch do %>

	<% @products.each do |product| %>
		<h3>商品名稱: <%= product.name %></h3>
		<p>庫存: <%= product.in_stocks %>, 安全存量: <%= product.safety_stocks %>,	
 		 增加數量:<%= text_field_tag "add_number[#{product.id}]" %> </p>
	<% end %>
	<%= submit_tag "補貨" %>
<% end %>

<%= link_to 'Back to main page', managers_path %>

app/views/managers/home.html.erb

<div class="center jumbotron">
  <h1>Welcome to the EC shopping</h1>

  <h2>請選擇以下身分登入</h2>

  <%= link_to "顧客登入", new_user_session_path, class: "btn btn-lg btn-primary" %>

  <%= link_to "管理者登入", new_member_session_path, class: "btn btn-lg btn-info" %>
</div>


<% if user_signed_in? %>
  <li>
   <%= link_to '返回電蝦首頁', managers_path %><br>    
  </li>
<% else %>
  <li>
   <%= link_to '會員註冊', new_user_registration_path %>
  </li>
<% end %>
<% if member_signed_in? %>
  <li>
   <%= link_to '返回電蝦首頁', managers_path %><br>     
  </li>
<% else %>
  <li>
   <%= link_to '管理者註冊', new_member_registration_path %>
  </li>
<% end %> 

app/views/managers/index.html.erb
<div class="container" style="width: 650px;">
  <% if user_signed_in? %>
    <h2><%= link_to 'Ready to shop', products_path %></h2>
  <% end %>
<%= render 'layouts/cart' %>


<% if member_signed_in? %>
<table class="table">
	<tr>
    <h3>You Are The Member</h3></tr>
  <tr>
    <th><%= link_to '管理使用者', uniusers_path %></th></tr>
	<tr>
    <th><%= link_to '管理商品', products_path %></th></tr>
	<tr>
    <th><%= link_to '管理商品類別', categories_path %></th></tr>
  <tr>
    <th><%= link_to '管理商品庫存', check_stock_path %></th></tr>
	<tr>
    <th><%= link_to('Logout', destroy_member_session_path, method: :delete) %></th></tr>
<% end %>

</table>

</div>

app/views/managers/show_date.html.erb
<body>
<% a = Time.now.to_s %>
<h1><%= a %></h1>

<div>
	How many days after today : <input type= "number" id = "myInput">
</div><br>

<button id = "CountDays">Count the days!</button><br>

	<h1>It's going to be : <div id = "afterCount"></div></h1>

<div>
	
</div>

</body>
<script>
	var moreDay = new Date();

	function addDay(y) {

		moreDay.setDate(Number(moreDay.getDate())+ Number(y) );
		return moreDay

	}	


	document.getElementById("CountDays").onclick = function () {

	var InputDays = document.getElementById("myInput").value;

		document.getElementById("afterCount").innerHTML = addDay(InputDays);
		}


</script>