config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  devise_for :users
  resources :uniusers
  resources :buy_records
  resources :managers do
    collection do
      get :check_out, path: 'check_out/:id'
      get :buy_record, path: 'buy_record/:id'
    end
  end
  resources :products
  resources :categories do
  	resources :products, :controller => 'categories'
  end
  resource :cart, only:[:show, :destroy] do
    collection do
      post :add, path: 'add/:id'
    end
  end
  root :to => "managers#home"
  get '/show_date' => 'managers#show_date', :as => "show_date"
  patch 'product_update/:id' => 'categories#product_update'
  post '/save_and_destroy' => 'carts#save_and_destroy'
  get '/check_stock' => 'managers#check_stock', :as => "check_stock"
  patch '/update_stock' => 'managers#update_stock', :as => "update_stock"
  patch '/add_user_money' => 'uniusers#add_user_money', :as => "add_user_money"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart
	attr_reader :items, :total

	def initialize(items = [])
		@items = items
	end

	def add_item(product_id)
		found_item = items.find { |item| item.product_id == product_id}
		
		if found_item
			found_item.increment
		else
		@items << CartItem.new(product_id)
		end
	end

	def empty?
		@items.empty?
	end

	def total_price
		items.reduce(0) { |sum, item| sum + item.price }
	end

	def serialize
		all_items = items.map { |item| 

			{ "product_id" => item.product_id, "quantity" => item.quantity }
		}
		{ "items" => all_items }
	end

	def self.from_hash(hash)
		if hash.nil?
			new []
		else
			new hash["items"].map { |item_hash|

				CartItem.new(item_hash["product_id"], item_hash["quantity"])
			}
		end
	end
end

app/models/cart_detail.rb
class CartDetail < ApplicationRecord
	belongs_to :cart_record
end

app/models/cart_item.rb
class CartItem
	attr_reader :product_id, :quantity

	def initialize(product_id, quantity = 1)
		@product_id = product_id
		@quantity = quantity
	end

	def increment(n = 1)
		@quantity += n
	end

	def product
		Product.find_by(id: product_id)
	end

	def price
		product.price * quantity
	end

end

app/models/cart_record.rb
class CartRecord < ApplicationRecord
	has_many :cart_details
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	delegate :name, :to => :category, :prefix => true, :allow_nil => true
end

app/models/replenish.rb
class Replenish < ApplicationRecord
end

app/models/replenish_detail.rb
class ReplenishDetail < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	def add

		current_cart.add_item(params[:id])
		session[:cart9999] = current_cart.serialize

		redirect_to products_path, notice: "#{Product.find(params[:id]).name} 已加入購物車"
	end
	def destroy
		session[:cart9999] = nil

		redirect_to products_path, notice: "購物車已清空"
	end

	def save_and_destroy

		if enough_money?(total)

			@cartrecord = CartRecord.new
			@cartrecord.user_id = current_user.id
			@cartrecord.user_name = current_user.name
			@cartrecord.total_price = current_cart.items.reduce(0) { |sum, item| sum + item.price }

			current_cart.items.each do |item|
				@cartdetail = @cartrecord.cart_details.build
				@cartdetail.product_name = item.product.name
				@cartdetail.quantity = item.quantity
				@cartdetail.unit_price = item.product.price
				@cartdetail.product_subtal = item.price
				@cartdetail.save
			end
			@cartrecord.save

			current_user.money -= total 
			current_user.save

			session[:cart9999] = nil
			redirect_to managers_path, notice: "已付款!於個人首頁查看訂單XXXX狀態" 
		else
			flash.now[:warning] = '餘額不足'
			render 'managers/index'
		end
	end

end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
	def home
	end
	def index
	end
	def create
	end

	def buy_record
		@buyrecords = CartRecord.all
	end
	
	def check_out
	end
	def show_date
		@b = Time.now
	end
	def update 
	end
	def check_stock
		@products = Product.where("in_stocks < safety_stocks")

	end
	def update_stock	
		@products = Product.where("in_stocks < safety_stocks")
		#in_stock 個別增加管理者輸入之值,save個別儲存
		@products.each do |product|
			params[:add_number].each do |key,value|
				puts product.id
				puts key
				puts value
				if key.to_i == product.id
				product.in_stocks += value.to_i
				end
			end
			product.save
		end
		redirect_to managers_path
	end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_action :set_product, :only => [ :show, :edit, :update, :destroy]
	def index
		@products = Product.all
	end
	def show
	end
	def edit
	end
	def update
		@product = Product.find(params[:id])
		@product.update(product_params)

		redirect_to product_url(@product)
	end
	def destroy
		@product.destroy

		flash[:warning] = "Product was destroyed!"
		redirect_to products_url
	end
	def new
		@product = Product.new
	end
	def create
		@product = Product.new(product_params)
		@product.save
		flash[:notice] = "Product was successfully created"

		redirect_to products_url
	end


	private
	def set_product
  		@product = Product.find(params[:id])
	end
	def product_params
	  params.require(:product).permit(:name, :description, :price, :category_id, :quantity, :in_stocks, :safety_stocks)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, :only => [ :show, :edit, :update, :destroy]
	def index
		@users = User.all
	end
	def new
		@user = User.new
	end
	def create
		@user = User.new(user_params)
		@user.save

		redirect_to users_url
	end
	def show
	end
	def edit
	end
	def update
		@user = User.find(params[:id])
		@user.update(user_params)

		redirect_to user_url(@user)
	end
	def destroy
		@user.destroy
		redirect_to users_url
	end


private
	def set_user
  		@user = User.find(params[:id])
	end
	def user_params
	  params.require(:user).permit(:email, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buy_records_helper.rb
module BuyRecordsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
	def current_cart
		@cart ||= Cart.from_hash(session[:cart9999])
	end

	def has_cart?
		!current_cart.items.empty?
	end

	def total
		current_cart.items.reduce(0) { |sum, item| sum + item.price }
	end


  def enough_money?(total_price)
  	current_user.money > total_price
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb
<h1>購物車</h1>

<%= link_to '清空購物車', cart_path, method: :delete %>

<table>
	<thead>
		<tr>
			<td>商品名稱</td>
			<td>數量</td>
			<td>單價</td>
			<td>小計</td>
		</tr>
	</thead>	

	<tbody>
		<% current_cart.items.each do |item| %>
		<tr>
			<td><%= item.product.name %></td>
			<td><%= item.quantity %></td>
			<td><%= item.product.price %></td>
			<td><%= item.price %></td>
		</tr>
		<% end %>
	</tbody>
	<br>
	<tfoot>
		<tr>
			<td colspan="3">總計</td>
			<td><%= current_cart.total_price %></td>
		</tr>
	</tfoot>
</table>


<%= link_to '繼續選購', products_path %>
<%= link_to '結帳', products_path %>

app/views/products/edit.html.erb
<%= form_for @product, :url => product_path(@product), :method => :patch do |f| %>

<%= render :partial => 'layouts/product', :locals => { :f => f} %>

	<%= f.select :category_id, Category.all.map{ |c| [c.name, c.id] } %><br>

	<%= f.submit "Update" %>
<% end %>

app/views/products/index.html.erb
<div class="container">
	<h1>商品列表</h1>
<table class="table" style="width: 600px;">
	<% @products.each do |pd| %>
	<tr>
	<td style="text-align: center"><%= pd.name %></td>
	<td style="width:130px;"><%= link_to 'See description', product_path(pd) %></td>
	<% if user_signed_in? %>
	<td style="width:130px;"><%= link_to '放到購物車', add_cart_path(pd), method: :post %></td>
	<% end %>

	<% if member_signed_in? %>
 		<td style="width:80px;"><%= link_to 'Edit', edit_product_path(pd) %></td>
		<td style="width:80px;"><%= link_to 'Delete', product_path(pd), :method => :delete, :data => { :confirm => 'Are you suer?'} %></td>    	
	<% end %>
	<% end %>
</table>
	<% if member_signed_in? %>
		<%= link_to 'Create new product', new_product_path %>
	<% end %>
	<% if user_signed_in? %>
	
		<%= link_to '檢查購物車', managers_path, :class => "btn btn-info" %>
	<% end %>
<br><br>
<%= link_to '回個人主頁', managers_path, :class => "btn btn-primary" %>

app/views/products/new.html.erb
<%= form_for @product, :url => products_path do |f| %>

<%= render :partial => 'layouts/product', :locals => { :f => f} %>
	
<%= f.collection_select(:category_id, Category.all, :id, :name) %><br>

	<%= f.submit "Create" %>
<% end %>

app/views/products/show.html.erb
<p>Name : <%= @product.name %></p>
<p> Price : <%= (@product.price) %></p>
<p>說明: <%= (@product.description) %><p>

<p>分類: <%= @product.category.name %></p> 

	<% if user_signed_in? %>
		<p>現有數量: <%= @product.quantity %></p> 	
		<%= link_to '放到購物車', add_cart_path(@product), method: :post %>
	<% end %>

	<% if member_signed_in? %>
	
		<p>現有庫存量: <%= @product.in_stocks %></p>
		<p>安全存量: <%= @product.safety_stocks %></p>
	<% end %>


<p><%= link_to 'Back to index', products_path %></p>

app/views/users/edit.html.erb
<%= form_for @user, :url => user_path(@user), :method => :patch do |f| %>
    <%= f.label :email, "Email" %>
    <%= f.text_field :email %>

    <%= f.label :password, "Password" %>
    <%= f.text_area :password %>

    <%= f.submit "Update" %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user, :url => users_path do |f| %>
	<%= f.label :email, "Email" %>
    <%= f.text_field :email %>

    <%= f.label :password, "Password" %>
    <%= f.text_area :password %>

    <%= f.submit "Create" %>
<% end %>

app/views/users/show.html.erb
<%= @user.email %>

<p>user_id : <%= (@user.id) %> </p> 

<p><%= link_to 'Back to index', users_path %></p>