config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  devise_for :users
  resources :uniusers
  resources :buy_records
  resources :managers do
    collection do
      get :check_out, path: 'check_out/:id'
      get :buy_record, path: 'buy_record/:id'
    end
  end
  resources :products
  resources :categories do
  	resources :products, :controller => 'categories'
  end
  resource :cart, only:[:show, :destroy] do
    collection do
      post :add, path: 'add/:id'
    end
  end
  root :to => "managers#home"
  get '/show_date' => 'managers#show_date', :as => "show_date"
  patch 'product_update/:id' => 'categories#product_update'
  post '/save_and_destroy' => 'carts#save_and_destroy'
  get '/check_stock' => 'managers#check_stock', :as => "check_stock"
  patch '/update_stock' => 'managers#update_stock', :as => "update_stock"
  patch '/add_user_money' => 'uniusers#add_user_money', :as => "add_user_money"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart
	attr_reader :items, :total

	def initialize(items = [])
		@items = items
	end

	def add_item(product_id)
		found_item = items.find { |item| item.product_id == product_id}
		
		if found_item
			found_item.increment
		else
		@items << CartItem.new(product_id)
		end
	end

	def empty?
		@items.empty?
	end

	def total_price
		items.reduce(0) { |sum, item| sum + item.price }
	end

	def serialize
		all_items = items.map { |item| 

			{ "product_id" => item.product_id, "quantity" => item.quantity }
		}
		{ "items" => all_items }
	end

	def self.from_hash(hash)
		if hash.nil?
			new []
		else
			new hash["items"].map { |item_hash|

				CartItem.new(item_hash["product_id"], item_hash["quantity"])
			}
		end
	end
end

app/models/cart_detail.rb
class CartDetail < ApplicationRecord
	belongs_to :cart_record
end

app/models/cart_item.rb
class CartItem
	attr_reader :product_id, :quantity

	def initialize(product_id, quantity = 1)
		@product_id = product_id
		@quantity = quantity
	end

	def increment(n = 1)
		@quantity += n
	end

	def product
		Product.find_by(id: product_id)
	end

	def price
		product.price * quantity
	end

end

app/models/cart_record.rb
class CartRecord < ApplicationRecord
	has_many :cart_details
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	delegate :name, :to => :category, :prefix => true, :allow_nil => true
end

app/models/replenish.rb
class Replenish < ApplicationRecord
end

app/models/replenish_detail.rb
class ReplenishDetail < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	def add

		current_cart.add_item(params[:id])
		session[:cart9999] = current_cart.serialize

		redirect_to products_path, notice: "#{Product.find(params[:id]).name} 已加入購物車"
	end
	def destroy
		session[:cart9999] = nil

		redirect_to products_path, notice: "購物車已清空"
	end

	def save_and_destroy

		if enough_money?(total)

			@cartrecord = CartRecord.new
			@cartrecord.user_id = current_user.id
			@cartrecord.user_name = current_user.name
			@cartrecord.total_price = current_cart.items.reduce(0) { |sum, item| sum + item.price }

			current_cart.items.each do |item|
				@cartdetail = @cartrecord.cart_details.build
				@cartdetail.product_name = item.product.name
				@cartdetail.quantity = item.quantity
				@cartdetail.unit_price = item.product.price
				@cartdetail.product_subtal = item.price
				@cartdetail.save
			end
			@cartrecord.save

			current_user.money -= total 
			current_user.save

			session[:cart9999] = nil
			redirect_to managers_path, notice: "已付款!於個人首頁查看訂單XXXX狀態" 
		else
			flash.now[:warning] = '餘額不足'
			render 'managers/index'
		end
	end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :set_category, :only => [:show, :edit, :update, :destroy]

	def index
		@categories = Category.all
		@category = Category.new

	end
	def show
		@need_products = @category.products
	end
	def edit		
	end
	def update
		@category = Category.find(params[:id])
		@category.update(category_params)

		redirect_to category_path(@category)
	end
	def new
		@category = Category.new
	end
	def create
		@category = Category.new(category_params)

		respond_to do |format|
			if @category.save
				format.html { redirect_to @category, notice: '成功產生新類別'}
				format.js
				format.json { render json: @category, status: :create, location: @category}
			end
		end
	end
	
	def destroy
		@category.destroy

		redirect_to categories_path
	end
	def product_update
		@product = Product.find(params["product"][:id])
		@product.update(product_params)

		redirect_to categories_path
	end

	private
	def set_category
		@category = Category.find(params[:id])
		@category_products = Product.all
	end
	def category_params
		params.require(:category).permit(:name)
	end
	def product_params
	  params.require(:product).permit(:name, :description, :price, :category_id, :id)
	end

	protected

end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
	def home
	end
	def index
	end
	def create
	end

	def buy_record
		@buyrecords = CartRecord.all
	end
	
	def check_out
	end
	def show_date
		@b = Time.now
	end
	def update 
	end
	def check_stock
		@products = Product.where("in_stocks < safety_stocks")

	end
	def update_stock	
		@products = Product.where("in_stocks < safety_stocks")
		#in_stock 個別增加管理者輸入之值,save個別儲存
		@products.each do |product|
			params[:add_number].each do |key,value|
				puts product.id
				puts key
				puts value
				if key.to_i == product.id
				product.in_stocks += value.to_i
				end
			end
			product.save
		end
		redirect_to managers_path
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, :only => [ :show, :edit, :update, :destroy]
	def index
		@users = User.all
	end
	def new
		@user = User.new
	end
	def create
		@user = User.new(user_params)
		@user.save

		redirect_to users_url
	end
	def show
	end
	def edit
	end
	def update
		@user = User.find(params[:id])
		@user.update(user_params)

		redirect_to user_url(@user)
	end
	def destroy
		@user.destroy
		redirect_to users_url
	end


private
	def set_user
  		@user = User.find(params[:id])
	end
	def user_params
	  params.require(:user).permit(:email, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buy_records_helper.rb
module BuyRecordsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
	def current_cart
		@cart ||= Cart.from_hash(session[:cart9999])
	end

	def has_cart?
		!current_cart.items.empty?
	end

	def total
		current_cart.items.reduce(0) { |sum, item| sum + item.price }
	end


  def enough_money?(total_price)
  	current_user.money > total_price
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<span style="font-size: 1.5em;"><%= c.name %></span>
<%= link_to 'Show', category_path(c) %>
<%= link_to 'Edit', edit_category_path(c) %>
<%= link_to 'Destroy', category_path(c), :method => :delete %>

app/views/categories/create.js.erb
$("<%= escape_javascript(render :partial => 'categories/category', :locals => { :c => @category}) %></li>").appendTo("#categories")

app/views/categories/edit.html.erb
<%= form_for @category, :url => category_path(@category), :method => :patch do |f| %>
	<%= f.label :name, "Name" %>
	<%= f.text_field :name %>

	<%= f.submit "Update" %>
<% end %>

<%= link_to 'Back to manage category', categories_path %>

app/views/categories/index.html.erb
<div class="container">

	<ul id="categories">
		<% @categories.each do |c| %>
			<li>
			<%= render :partial => 'categories/category', :locals => { :c => c} %>		
			</li>
		<% end %>
	</ul>
</div>

<div class="hide_container">
    <div class="slide_header"><span>產生新類別</span>
		</div>
    <div class="content">
			<%= form_with(model: @category) do |f| %>
				<%= f.label :name, "Name:" %>
				<%= f.text_field :name %>

			<%= f.submit "產生" %>
<% end %>
	        
    </div>
</div>

<%= link_to 'Back to main page', managers_path %>


<script type="text/javascript">
	$(".slide_header").click(function () {

    $header = $(this);
    //getting the next element
    $content = $header.next();
    //open up the content needed - toggle the slide- if visible, slide up, if not slidedown.
    $content.slideToggle(500, function () {
        //execute this after slideToggle is done
        //change text of header based on visibility of content div
        $header.text(function () {
            //change text based on condition
            return $content.is(":visible") ? "收起" : "產生新類別";
        });
    });

	});
</script>

app/views/categories/new.html.erb
<%= form_for @category, :url => categories_path do |f| %>
	<%= f.label :name, "Name" %>
	<%= f.text_field :name %>

	<%= f.submit "Create" %>
<% end %>

<%= link_to 'Back to manage category', categories_path %>

app/views/categories/show.html.erb
<%= @category.name %><br>


		<% @need_products.each do |cp| %>
	<li>

		<%= cp.name %>
		<%= form_for cp, :url => { :controller => 'categories', :action => 'product_update'} do |f| %>
		<%= f.hidden_field :id %>
		<%= f.collection_select(:category_id, Category.all, :id, :name) %>

		<%= f.submit "Change" %>
		<% end %>
	</li>
		<% end %>




<%= link_to 'Back to manage category', categories_path %>