config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  devise_for :users
  resources :uniusers
  resources :buy_records
  resources :managers do
    collection do
      get :check_out, path: 'check_out/:id'
      get :buy_record, path: 'buy_record/:id'
    end
  end
  resources :products
  resources :categories do
  	resources :products, :controller => 'categories'
  end
  resource :cart, only:[:show, :destroy] do
    collection do
      post :add, path: 'add/:id'
    end
  end
  root :to => "managers#home"
  get '/show_date' => 'managers#show_date', :as => "show_date"
  patch 'product_update/:id' => 'categories#product_update'
  post '/save_and_destroy' => 'carts#save_and_destroy'
  get '/check_stock' => 'managers#check_stock', :as => "check_stock"
  patch '/update_stock' => 'managers#update_stock', :as => "update_stock"
  patch '/add_user_money' => 'uniusers#add_user_money', :as => "add_user_money"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart
	attr_reader :items, :total

	def initialize(items = [])
		@items = items
	end

	def add_item(product_id)
		found_item = items.find { |item| item.product_id == product_id}
		
		if found_item
			found_item.increment
		else
		@items << CartItem.new(product_id)
		end
	end

	def empty?
		@items.empty?
	end

	def total_price
		items.reduce(0) { |sum, item| sum + item.price }
	end

	def serialize
		all_items = items.map { |item| 

			{ "product_id" => item.product_id, "quantity" => item.quantity }
		}
		{ "items" => all_items }
	end

	def self.from_hash(hash)
		if hash.nil?
			new []
		else
			new hash["items"].map { |item_hash|

				CartItem.new(item_hash["product_id"], item_hash["quantity"])
			}
		end
	end
end

app/models/cart_detail.rb
class CartDetail < ApplicationRecord
	belongs_to :cart_record
end

app/models/cart_item.rb
class CartItem
	attr_reader :product_id, :quantity

	def initialize(product_id, quantity = 1)
		@product_id = product_id
		@quantity = quantity
	end

	def increment(n = 1)
		@quantity += n
	end

	def product
		Product.find_by(id: product_id)
	end

	def price
		product.price * quantity
	end

end

app/models/cart_record.rb
class CartRecord < ApplicationRecord
	has_many :cart_details
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	delegate :name, :to => :category, :prefix => true, :allow_nil => true
end

app/models/replenish.rb
class Replenish < ApplicationRecord
end

app/models/replenish_detail.rb
class ReplenishDetail < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	def add

		current_cart.add_item(params[:id])
		session[:cart9999] = current_cart.serialize

		redirect_to products_path, notice: "#{Product.find(params[:id]).name} 已加入購物車"
	end
	def destroy
		session[:cart9999] = nil

		redirect_to products_path, notice: "購物車已清空"
	end

	def save_and_destroy

		if enough_money?(total)

			@cartrecord = CartRecord.new
			@cartrecord.user_id = current_user.id
			@cartrecord.user_name = current_user.name
			@cartrecord.total_price = current_cart.items.reduce(0) { |sum, item| sum + item.price }

			current_cart.items.each do |item|
				@cartdetail = @cartrecord.cart_details.build
				@cartdetail.product_name = item.product.name
				@cartdetail.quantity = item.quantity
				@cartdetail.unit_price = item.product.price
				@cartdetail.product_subtal = item.price
				@cartdetail.save
			end
			@cartrecord.save

			current_user.money -= total 
			current_user.save

			session[:cart9999] = nil
			redirect_to managers_path, notice: "已付款!於個人首頁查看訂單XXXX狀態" 
		else
			flash.now[:warning] = '餘額不足'
			render 'managers/index'
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buy_records_helper.rb
module BuyRecordsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
	def current_cart
		@cart ||= Cart.from_hash(session[:cart9999])
	end

	def has_cart?
		!current_cart.items.empty?
	end

	def total
		current_cart.items.reduce(0) { |sum, item| sum + item.price }
	end


  def enough_money?(total_price)
  	current_user.money > total_price
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_cart.html.erb
<% if has_cart? %>
<h1>購物車</h1>

<%= link_to '清空購物車', cart_path, method: :delete %>
<table class="table">
  <thead>
    <tr>
      <td>商品名稱</td>
      <td>數量</td>
      <td>單價</td>
      <td>小計</td>
    </tr>
  </thead>  

  <tbody>
    <% current_cart.items.each do |item| %>
    <tr>
      <td><%= item.product.name %></td>
      <td><%= item.quantity %></td>
      <td><%= item.product.price %></td>
      <td><%= item.price %></td>
    </tr>
    <% end %>
  </tbody>
  <br>
  <tfoot>
    <tr>
      <td colspan="3">總計</td>
      <td><%= current_cart.total_price %></td>
    </tr>
  </tfoot>

</table>

<%= link_to '結帳', save_and_destroy_path, :method => :post %>

<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "EC shopping", '#', id: "logo" %> 
    <nav>
      <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", managers_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to('Check date', show_date_path) %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", uniuser_path(current_user) %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li><%= link_to('購物紀錄', buy_record_managers_path(current_user)) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
      <% end %>
    </nav>
  </div>
</header>

app/views/layouts/_product.html.erb

	<%= f.label :name, "Name" %>
	<%= f.text_field :name %><br>
	<%= f.label :description, "Description" %>
	<%= f.text_area :description %><br>
	<%= f.label :price, "Price" %>
	<%= f.text_field :price %><br>
	<%= f.label :in_stocks, "現有庫存量" %>
	<%= f.text_field :in_stocks %><br>
	<%= f.label :safety_stocks, "安全存貨" %>
	<%= f.text_field :safety_stocks %><br>

app/views/layouts/_user.html.erb
	<%= f.label :name, "Name" %>
  <%= f.text_field :name %>

	<%= f.label :email, "Email" %>
  <%= f.text_field :email %>

  <%= f.label :password, "Password" %>
  <%= f.text_area :password %>

	<%= f.label :money, "Money" %>
  <%= f.text_field :money %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ec</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% if flash[:notice].present? %>
      <div class="alert alert-success alert-dismissible fade in" role="alert">
        <%= flash[:notice] %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
      </div>
      <% end %>

      <% if flash[:warning].present? %>
      <div class="alert alert-danger alert-dismissible fade in" role="alert">
         <%= flash[:warning] %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <% end %>


    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>